### ISSUE TITLE
Use `bsdtar` to extract 7z source code archive?

### ISSUE THREAD

**Issue by ghost** [justdan96/7zip_static#1]
Although 7z source code is provided in 7z format, `bsdtar` should be able to extract it, so [maybe you don't have to re-package it into `.tar.gz`](https://github.com/justdan96/7zip_static/blob/main/Dockerfile#L19).

**Comment by justdan96** [comment]
Thank you @jo620kix that is a great spot! 

I didn't know bsdtar could handle 7z files but I've just tested it and it works great. I'll be pushing a new version of the Dockerfile with this change made very soon.

**Comment by justdan96** [comment]
Change committed as: https://github.com/justdan96/7zip_static/commit/625df5aeb69b40a847005f52afddb207eff15a98

**Comment by ghost** [comment]
@Karlson2k

I noticed your comment on SourceForge regarding that the source code is only available in 7z format.

For the time being, please try using `bsdtar` to extract the source code archive.

**Comment by jloqfjgk** [comment]
@danyspin97 (openSUSE 7zip package maintainer)
Regarding [your post on SourceForge](https://sourceforge.net/p/sevenzip/discussion/45797/thread/df012dffa9/) and the [7zip openSUSE build file](https://build.opensuse.org/package/view_file/Archiving/7zip/7zip.spec?expand=1), please consider using `bsdtar` for the time being.

`bsdtar` (libarchive) is able to extract 7z archives.

**Comment by danyspin97** [comment]
I wasn't aware that `bsdtar` was able to extract 7z archives. Thank you @jloqfjgk for the heads-up, I really appreciate it 😄

**Comment by jloqfjgk** [comment]
You are welcome.

By the way, as of 21.07 (which is just released), the source code is available in both formats: [7z](https://www.7-zip.org/a/7z2107-src.7z) and [.tar.xz](https://www.7-zip.org/a/7z2107-src.tar.xz).

**Comment by justdan96** [comment]
Good news!
