### ISSUE TITLE
UASM Build Errors with Clang 11

### ISSUE THREAD

**Issue by wxlg1117** [justdan96/7zip_static#2]
"docker build -t 7zip_static . 2>&1 | tee build.log " with numerous errors ...
[build.log](https://github.com/justdan96/7zip_static/files/7271093/build.log)

**Comment by justdan96** [comment]
This issue appears to be related to this one in UASM: https://github.com/Terraspace/UASM/issues/143

I guess when I ran it last LLVM and Clang were not at version 11!  This fix is apparently contained in this PR: https://github.com/Terraspace/UASM/pull/144

I _think_ it is the `'#pragma once` directives. I'll need to investigate a bit more, but until then I will pin Clang and LLVM to version 10.

Edit: the fix may actually be a lot easier than I thought: https://github.com/hfp/libxsmm/issues/412

**Comment by justdan96** [comment]
@wxlg1117 can you please check if the issue still occurs after merging the PR #4?

**Comment by wxlg1117** [comment]
> 
> 
> @wxlg1117 can you please check if the issue still occurs after merging the PR #4?

perfect with no error.
